### ISSUE TITLE
HP MP etc. boxes just show green rectangle without numbers

### ISSUE THREAD

**Issue by sakipvp** [SDClowen/RSBot#102]

**Comment by SDClowen** [comment]
I'm so sorry dude but when you open a issue or anything really i don't understand. Can you explain a little more what you want to say with photos?

**Comment by Ahmed0425** [comment]
@SDClowen Actually I got what he meant, The problem is about parsing the right icon image

![Untitled](https://user-images.githubusercontent.com/25909799/159845085-4b9b6ff4-7ab8-4d67-85db-abeec917d04e.jpg)

**Comment by SDClowen** [comment]
Hmm. You are right. I will look to the problem as soon as got a free time.
