### ISSUE TITLE
pt from ve fellow pet bolumu duzeltilmesi gerekiyor

### ISSUE THREAD

**Issue by Destanbek** [SDClowen/RSBot#110]
parti form ayarlarında eksiklik var yeni sürümde bozulmuş ekleyince eksik ekliyor silince yeniden eklemiyor birde Csro-r isro gibi orjinal surumlerde fellow pet gostergesinde gostermıyor sadece eski attack petlerinki aktif.

**Comment by SDClowen** [comment]
Rica ediyorum her problem için bir tane issue oluşturun. Tüm problemlerinizi tek bir issue'ye sığdırmayın. Ayrıca Yeni sürüm yayınlanmadan ana kaynak kodu üzerindeki problemler burada issue olarak oluşturulmaması gerekir. Bunun duyurusunu daha öncede yaptım. En son 1.7 yayınlandıysa sadece 1.7b release'nin üzerindeki problemler issue olarak kabul edilir.
