### ISSUE TITLE
Euro in general didn't switch weapons to buff and Warlock skills issue 

### ISSUE THREAD

**Issue by Octopain** [SDClowen/RSBot#112]
Euro in general didn't switch weapons to buff and Warlock skills issue  

Euro in general didn't switch weapons to buff and Warlock skills didn't show up to use it in attack just 2 skills shows Blood and Death Flower  the rest of debuff skills didn't show up

**Comment by mrdezner** [comment]
I would also like to see the warlock skills working.

**Comment by SDClowen** [comment]
You can use the warlock attack skills. No have any problem.

**Comment by Octopain** [comment]
> You can use the warlock attack skills. No have any problem.

its just 2 skills for attack (Blood Flower - Death Flower ) and Death Flower has a delay so no way 
also the fun for playing Warlock is Debuff Skills

**Comment by andersonbsp** [comment]
hey do you think about doing full support for warlock?

**Comment by SDClowen** [comment]
RSBot not have full debuffs support. So its not warlock related. I will support in soon. Also weapons switchs no have any problem. I tested alot of time.
