### ISSUE TITLE
The bot doesn't show imbue skills in Shiroi (CSRO-R)

### ISSUE THREAD

**Issue by Ahmed0425** [SDClowen/RSBot#116]
![Imbue](https://user-images.githubusercontent.com/25909799/160716162-4532d77c-3ca8-42c7-9e53-7314d6ab1955.jpg)

**Comment by SDClowen** [comment]
I don't think this issue is caused by RSBot.

**CSRO-R Standart Files**
![image](https://user-images.githubusercontent.com/14323838/160731881-fb8807d5-ea75-437c-a4f4-cd9c8d1173df.png)

**Comment by SDClowen** [comment]
I dont know. Maybe imbues not working like original imbues. So maybe data values are different.
