### ISSUE TITLE
TR SRO Clone Map DC Problemi

### ISSUE THREAD

**Issue by akulleci** [SDClowen/RSBot#118]
Clone mapte iken ilk oyuna girişte oyundan atıyor. Daha sonrasında oyuna tekrar giriş yaptığımız zaman char oyunda hatası veriyor.

**Comment by SDClowen** [comment]
Bu problemin RSBot ile alakası olduğunu düşünmüyorum. Çünkü bir çok kullanıcı RSBot kullanmayanlarda bile hesap zaten oyunda hatası veriyor. İstemci klasöründe yer alan dump klasörünü zipleyip ilgili yetkililere göndermenizi  tavsiye ediyorum.
