### ISSUE TITLE
When TrSRO client restart after dc, it gets stuck at login title screen and doesn't activate automated login

### ISSUE THREAD

**Issue by Ahmed0425** [SDClowen/RSBot#126]
When TrSRO client gets dc for some reason (router restart, say) and the bot restarts the client, it doesn't activate automated login and it gets stuck at login title screen without entering credentials
the bot should make multiple tries until logging in succeed or simply check if there's internet connection to login

**Comment by akulleci** [comment]
Also, it gives a c10 error when I log in to the game manually while  auto login is active.  The next is known "Account already in game". :D
