### ISSUE TITLE
Custom colors in theme color selector when added are not saved for later use

### ISSUE THREAD

**Issue by Ahmed0425** [SDClowen/RSBot#130]

**Comment by SDClowen** [comment]
Tested working.

**Comment by Ahmed0425** [comment]
@SDClowen Are you speaking about this?
![Untitled](https://user-images.githubusercontent.com/25909799/161879618-08d0a272-5fbe-4fd6-834c-37f3400a0fa1.jpg)
no bro, I'm not able to save any color there .. they're always get reset
