### ISSUE TITLE
Issue's RSbot1.3b

### ISSUE THREAD

**Issue by GMDevelope** [SDClowen/RSBot#14]
-Guild Emblem white
-Bot stop itself
-could not select entity 0x4
-invalid skill error code 0x3005
-will be good to add all avaivable skills for res
-will be good to add skill devil spirit

**Comment by Ahmed0425** [comment]
Next time please make a separate issue for each problem

**Comment by SDClowen** [comment]
Talk with your server master about guild amblems. Its not related with us
