### ISSUE TITLE
about PK2 password

### ISSUE THREAD

**Issue by yxlong** [SDClowen/RSBot#161]
If I don't know the PK2 password, will I not be able to use this program?
When i run the program i get this error,i guess the pk2 password wrong.
I look forward to receiving your reply。
Thanks!!
![20220412161850](https://user-images.githubusercontent.com/4566574/162914770-d166b4c2-65e0-4afc-b20c-8ac32a43ed33.png)

**Comment by SDClowen** [comment]
You can configure your pk2 key in *config.rs* file in RSBot binary folder. Key Name is *RSBot.Pk2Key*

**Comment by yxlong** [comment]
thank u
