### ISSUE TITLE
client closes When buying shop TRSRO

### ISSUE THREAD

**Issue by TheRock2007** [SDClowen/RSBot#183]
There is a problem specifically when buying things from the shop
client closes
TRSRO 

Last update ver

**Comment by SDClowen** [comment]
Fixed

**Comment by TheRock2007** [comment]
not fixed

**Comment by akulleci** [comment]
> not fixed
> 
> When you buy anything from potion or stable client closes TRSRO

did u rebuild solution ? or still try on v1.9b ? if u try to v1.9b please wait to v2.0 releases.

**Comment by TheRock2007** [comment]
I am using the latest update 2.0
