### ISSUE TITLE
Script Sorunu

### ISSUE THREAD

**Issue by eroltenlik** [SDClowen/RSBot#185]
Merhaba, 
At ile script cizmek istedigimiz zaman script ekranına kordinatlar gelmiyor ve karakteri koşturarak script cizdigimizde kordinatlar geliyor herhangi bir problem yok fakat karakter townlop u yapip slota gitmek için malum o scripti kullandiği için char alışveris döngüsünede at aldiriyoruz slota hızlı gitmesi için onuda training kısmından binek hayvan varsa kullan a tick koyup baslattigimizda karakter at ın üstünde bekliyor slota gitmiyor townda bekliyor düzeltilirse iyi olur.

**Comment by SDClowen** [comment]
Fixed
