### ISSUE TITLE
Petteki eşyaları bankaya koymuyor

### ISSUE THREAD

**Issue by eroltenlik** [SDClowen/RSBot#192]
pet bazen topluyor bazen toplamiyor ve pet ayarlarini yaptigim zaman char town a döndügü zaman petteki itemleri bankaya koymuyor

**Comment by winlith** [comment]
translation of OP's message by google:

> The pet sometimes collects and sometimes does not collect and when I make the pet settings, it does not put the items in the pet into the bank when it returns to char town.

I'll try to implement storing items from pet's inventory

**Comment by winlith** [comment]
check https://github.com/SDClowen/RSBot/pull/235
