### ISSUE TITLE
iSRO issues

### ISSUE THREAD

**Issue by Khaled-Shawky** [SDClowen/RSBot#207]
First of all, Thank you for the great work you are doing.
I just have some comments of you don't mind me :)
I don't know if someone reported the same issues or not, so excuse me .

Auto login is not working .

Add section for re-supply (potions, arrows, etc...) for players under Lv70 in town script (iSRO).

Add more options in [skills section], for walk-back buffs.

[ Protection section ] use universal pills not working.

in Bow skill casting, it cast only one skill per monster and the rest are normal attack [ imagine killing Gaint with normal attack :) ].

in berzerk section, you need to categorize the berzerk , I might need to use with some certain monster type ( Gaint, Gaint party, Uniques, etc ....).

for iSRO you need to add a user defined timer, after timer finish, use return scroll and then relog, to reset the Shared Fatigue time.

in avoidance section, use check boxes for each choice (either avoid or prefer).

[ Party section ] add [ Auto form party, and auto reform ] add text box for party description while registering in party matching.

Add [ Auto stat point ] when level up, and [Auto skill] with gap, defined by the user.

attack skills and buffs list cleared if you raised the skills.

imbue is not updated if u raise the skill.

in record script, record everything, even talking to NPC (accepting repeatable quests).

Add trace option.

**Comment by SDClowen** [comment]
Next time, try open issue for each problem! This is not a forum site. Also there already have issues like your problem, so before open a issue check the issue list!
