### ISSUE TITLE
Can talk to teleports.

### ISSUE THREAD

**Issue by NickKlock** [SDClowen/RSBot#25]
When the bot is not running and I try to teleport from town to town I cant use the Teleport.(Not seeing the options.)

`System.IO.EndOfStreamException: Über das Ende des Datenstroms hinaus kann nicht gelesen werden.
   bei System.IO.BinaryReader.ReadByte()
   bei RSBot.Core.Network.Packet.ReadByteArray(Int32 count) in E:\Development\c#\RSBot\Library\RSBot.Core\Network\Packet.cs:Zeile 594.
   bei RSBot.Core.Objects.NpcTalk.Deserialize(Packet packet) in E:\Development\c#\RSBot\Library\RSBot.Core\Objects\NpcTalk.cs:Zeile 37.
   bei RSBot.Core.Objects.SelectedGameEntity.FromPacket(Packet packet) in E:\Development\c#\RSBot\Library\RSBot.Core\Objects\SelectedGameEntity.cs:Zeile 129.
   bei RSBot.Core.Network.Handler.Agent.Action.ActionSelectResponse.Invoke(Packet packet) in E:\Development\c#\RSBot\Library\RSBot.Core\Network\Handler\Agent\Action\ActionSelectResponse.cs:Zeile 33.
   bei RSBot.Core.Network.PacketManager.CallHandler(Packet packet, PacketDestination destination) in E:\Development\c#\RSBot\Library\RSBot.Core\Network\PacketManager.cs:Zeile 85.
   bei RSBot.Core.Network.Proxy.Server_OnPacketReceived(Packet packet) in E:\Development\c#\RSBot\Library\RSBot.Core\Network\Socket\Proxy.cs:Zeile 234.`

**Comment by NickKlock** [comment]
actually made an easy fix myself. Resetting the postion to 0 of the reader fixed it.
`public byte[] ReadByteArray(int count)
        {
            lock (_lock)
            {
                if (!Locked)
                    throw new PacketException(this, "Cannot Read from an unlocked Packet.");

                var values = new byte[count];
                _reader.BaseStream.Position = 0;
                for (var x = 0; x < count; ++x)
                    values[x] = _reader.ReadByte();

                return values;
            }
        }`

**Comment by Ahmed0425** [comment]
Actually the bug isn't about teleports, it's about all NPCs in general and the bot closes their windows automatically
That's a reported and known bug
