### ISSUE TITLE
every time  Disconnected login TRSRO

### ISSUE THREAD

**Issue by TheRock2007** [SDClowen/RSBot#289]
Client does not open Disconnected

Or when opening after adding ID PW
 given Disconnected

![XX1](https://user-images.githubusercontent.com/87621651/172017142-40384a0d-8045-4d6b-adcf-b28f0cbd2df7.png)

**Comment by SDClowen** [comment]
No have any problem. I think your network died while you are tried. Still have this problem?

**Comment by Ahmed0425** [comment]
@SDClowen This DC happens during login waiting time on an account with no premium activated
I'm not sure about the first case though since I never encountered it with the account @TheRock2007 provided me
