### ISSUE TITLE
TRSRO HPsi Yüksek Moblarda Common Atak Problemi

### ISSUE THREAD

**Issue by akulleci** [SDClowen/RSBot#334]
Giant genaral party  Giant party gibi moblarda skill yerine düz vuruş yapıyor. Melee charlarda düz vuruş problemi hala devam ediyor.
Edit: Atak yaptığı moba skill listesindeki tüm skilleri kullandığı zaman tekrardan skill kullanmıyor. Normal atağa devam ediyor. Genelde yüksek hpli moblarda yapıyor.

**Comment by akulleci** [comment]
Aynı moba skill listesindeki tüm skilleri kullandığı zaman tekrardan skill kullanmıyor. Normal atağa devam ediyor.

**Comment by SDClowen** [comment]
Skill müsait değilse common attak kullanır. Böyle bir probleminiz var ise Skill listesini çoğaltın.

**Comment by akulleci** [comment]
Hocam skillin müsaitliği ile ilgisi yok. 1. Skili bastı cooldown 3sn 2. Skili bastı cooldown 2sn. 3. Skilin ise 1 sn. Tekrar dönüp 1. Skili basacağına common attakta takılı kalıp sürekli mob ölene kadar öyle vuruyor. Wizard da ya da nukerde böyle problem yok ama bow ve xbowda mevcut.  Akşam warrior ve diğer ch str charlarda da deneyeceğim.

**Comment by warofmine** [comment]
Bow da bir sorun var skilleri vurduktan sonra common atak başliyor . ondan dolayı yapiyor olabilir bunu. oto takip te de misal sorun veren bir durumdu.
