### ISSUE TITLE
El Yakma Problemi

### ISSUE THREAD

**Issue by debelemez** [SDClowen/RSBot#377]
Fire el yakması süresi bitmesine rağmen, bot'un içinde aktif bufflarda açık gözüküyor. aktif gördüğü için el yakmıyor.

**Comment by debelemez** [comment]
Sonrasında Cold ile denedim sonuç aynı el yakma problemi devam ediyor

**Comment by Egezenn** [comment]
Bu sadece el yakma için geçerli değil, tüm bufflar sapıtabiliyor aynı şekilde ve bir daha bot tarafından kullanılmıyor.

Wiki'de > https://github.com/SDClowen/RSBot/wiki/05.-Skills-tab#active-buffs

```[bug] Sometimes bot won’t recognize expiration of buffs, and they won’t be cast. To fix this you have to teleport.```

**Comment by debelemez** [comment]
Peki bunu düzeltmenin yolu yok mu? 5 dk'da bir teleport mu olmamız lazım.
