### ISSUE TITLE
RSBot Release v2.1 TRSro client problem

### ISSUE THREAD

**Issue by Astronaut-eee** [SDClowen/RSBot#382]
Bot üzerinden açılan client malesef redirect olmuyor. Açılan client doğrudan orjinal gw adresine bağlanıyor. Bot için gerekli client 127.0.0.1:1500 ip ve portu ile loader kullanılıp açılacak olursa karakter oyuna giriyor fakat botun açtığı clientin kapanması durumunda bot proxyi sonlandırıp karakterin DC yemesine sebep oluyor. Redirect işlemi için yardımcı olabilir diyerek bir respostory paylaşıyorum. İncelemenizde fayda olduğunu düşünüyorum.

https://github.com/ProtonOverflow/NoAnkama

**Comment by SDClowen** [comment]
Emeğiniz için çok teşekkür ederim. O repository en kısa zamanda test edeceğim.
