### ISSUE TITLE
Bot doesn't work with CSRO anymore since Alchemy botbase got added

### ISSUE THREAD

**Issue by BaroDevelopment** [SDClowen/RSBot#383]
Bot doesn't work with CSRO anymore since Alchemy botbase got added

I can login  but bot is not loading anything - skills, inventory etc. .. everything is empty. Also HP AND MP not showing.

![image](https://user-images.githubusercontent.com/8499987/184551799-61f6b790-e771-48f1-8b83-76ddff185d79.png)

in the picture u see i am already logged into the game!

**Comment by SDClowen** [comment]
Do not open any issue if you find any bug at source code. The issues only accepting from release.
