### ISSUE TITLE
dotnet 6.0 not found but i have installed

### ISSUE THREAD

**Issue by yxlong** [SDClowen/RSBot#387]
![image](https://user-images.githubusercontent.com/4566574/184570282-af7bcad0-1b4e-469b-a508-11e0eea89ebf.png)

![image](https://user-images.githubusercontent.com/4566574/184570058-5fb8731d-059c-4cae-94e3-9dd68691f68e.png)

I change the json file item "6.0.0"->"6.0.8", It still doesn't work。

how deal this error ，Thanks!

**Comment by SDClowen** [comment]
You are installed SDK. For The bot, you have to install the [.net 6 desktop runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.8-windows-x86-installer).
