### ISSUE TITLE
walking around bug

### ISSUE THREAD

**Issue by mertyeni** [SDClowen/RSBot#411]
ptde sadece buff basmak istiyorum eski sürümde sıkıntı yoktu ama hiç durmadan koşuyor merkezi de 0 yapınca sol aşağıda da walking around yazıyor ve durmuyor

**Comment by ngoedde** [comment]
DeepL translation:
I just want to press the buff in pt, there was no problem in the old version, but it runs without stopping, when I make the center 0, it says walking around at the bottom left and does not stop.

**Comment by SDClowen** [comment]
@mertyeni Training tab üzerinde `Walkback to center` seçeneğini işaretleyin. Skills tab üzerinde _`No Attack (Attack Yapma)`_ seçeneğini işaretleyin.

@RamezAnton you can chose `Walkback to center` on **Training** tab
