### ISSUE TITLE
Item pickup iSro

### ISSUE THREAD

**Issue by medohatem** [SDClowen/RSBot#414]
The bot don't pickup any items on ground dropped by mobs that's including quest item and token like monk and solider
I dont have pet so i cant test it with grap pet but by character nothing is picked-up
Thanks again for your bot 
Best regards 
![Screenshot (185)](https://user-images.githubusercontent.com/9139944/189970350-588defc0-fc75-45dd-b6b3-148eb9a633eb.png)
![Screenshot (187)](https://user-images.githubusercontent.com/9139944/189970393-40653237-935e-469c-b604-05968e9b381e.png)

**Comment by dezio61** [comment]
Additional info, OwnerId of token is not same as playerJid

**Comment by SDClowen** [comment]
With last update, some isro spawn packets are changed by joymax. We are working on that.
