### ISSUE TITLE
In version 2.2 I can't find a window Training

### ISSUE THREAD

**Issue by magdyrashwan** [SDClowen/RSBot#422]
Hello sir
In version 2.2 I can't find a window Training
Attached is a copy of the previous version and the current version for clarification

Photo from issue No. 2.1
https://drive.google.com/file/d/1-wvPbA1dvsliIwtRAtv5T_V436neZLwl/view?usp=sharing
Photo from issue No. 2.2
https://drive.google.com/file/d/1cw9zX_CDHsZEVvLB5TRNMe5nj5jjYCK_/view?usp=sharing

Thank you very much dear sir

**Comment by BoerBart** [comment]
Hello magdyrashwan,

On the bottom left of version 2.2 it's showing "Alchemy", you can click it, then switch the bot to "RSBot". Once done, the "Alchemy" tab will be replaced by "Training".

**Comment by magdyrashwan** [comment]
> Hello magdyrashwan,
> 
> On the bottom left of version 2.2 it's showing "Alchemy", you can click it, then switch the bot to "RSBot". Once done, the "Alchemy" tab will be replaced by "Training".

Thank you very much
