### ISSUE TITLE
Where is the start button in a window Alchemy ?

### ISSUE THREAD

**Issue by magdyrashwan** [SDClowen/RSBot#426]
Hello sir @SDClowen 

please

I want a way to run Alchemy
Where is the start button in a window Alchemy ?

[`https://drive.google.com/file/d/1Gbl90UMSB_iH2tukdbQXjAsptHKWYvBm/view?usp=sharing`
](https://drive.google.com/file/d/1Gbl90UMSB_iH2tukdbQXjAsptHKWYvBm/view?usp=sharing)
Thank you very much

**Comment by SDClowen** [comment]
just start bot ^^

**Comment by magdyrashwan** [comment]
> just start bot like normal ^^

Yes, it works now, but you should have no return messages
When you have messages, they never work

Thank you very much

**Comment by SDClowen** [comment]
Enjoy :)
