### ISSUE TITLE
Add trace Selector

### ISSUE THREAD

**Issue by RamezAnton** [SDClowen/RSBot#430]
add a field to write the char name we need to trace all time 
example 
![image](https://user-images.githubusercontent.com/96068365/191837810-7af1e712-a2e6-4c95-8390-e55e831478de.png)
![image](https://user-images.githubusercontent.com/96068365/191837880-4c077b83-48d7-4e1a-93b3-8fb74918cf19.png)

**Comment by SDClowen** [comment]
#2 already have same issue.
