### ISSUE TITLE
optimize ram usage because take a lot of pc resources

### ISSUE THREAD

**Issue by Bfelo** [SDClowen/RSBot#454]
i notice that bot use alot of ram cause bot sometimes to stopped because i open another programs or anything in PC i have 8GB of ram mbot and sbot doesn't use alot of ram like Rsbot

**Comment by Munderstand101** [comment]
Yeah i have seen too i think its caused by this but no time to check in details :D 

https://learn.microsoft.com/en-us/troubleshoot/developer/dotnet/framework/general/winform-app-use-settooltip-not-release-memory

**Comment by SDClowen** [comment]
C'mon. According to RSBot client, it uses 60~130mb ram. Even the simplest program uses 150mb of ram. We live in 2022.

**Comment by SDClowen** [comment]
But dont worry, We will try to reduce it.

**Comment by Bfelo** [comment]
> But dont worry, We will try to reduce it.

sorry for late response as i said its cause if i open many characters bot stop or be slow in attack or pick maybe i got Disconnect too i knew that you try hard to make it fully optimize but i think this is a known issue for you and thank you for try to make bot work on low resources
