### ISSUE TITLE
Add option to prioritize adds 

### ISSUE THREAD

**Issue by dvdblk** [SDClowen/RSBot#495]
The bot should have an option to prioritize smaller mobs while killing giants (larger mobs). Currently the bot sticks to attacking a larger mob instead of prioritizing adds.

**Comment by ngoedde** [comment]
Yes, this is a nice feature! I thought about that by myself already. 

* In case of avoidance:
    * Order mobs attacking the player by rarity ascending
    * Select these mobs and kill them and then approach the giant again
    * ⚠️ Only mobs attacking the player should be attacked in this new case!
