### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by utku1676** [SDClowen/RSBot#519]
While we are clientless bot could return to the town then character invisible and bot crashed.

**Comment by SDClowen** [comment]
Sorununuzu kendi dilinizde tekrar açıklayın. İngilizce olarak yazdığınız `sorun konusu` hiç bir anlam ifade etmemektedir.

**Comment by utku1676** [comment]
clientlese geçip return çektiğinde bot town da gorunur olmuyor oyun yada bot kapanmıyor ama karakter ortada yok ve kasmaya devam etmıyor dolayısıyla sanırım 3012 paketi doğru zamanda gitmiyor
