### ISSUE TITLE
OTO  RESS

### ISSUE THREAD

**Issue by TheExecutorM** [SDClowen/RSBot#523]
Turkish:

beceriler gelişmiş bölümünde oto canlandir yerinde res skilini seçiyorum parti üyelerini oto canlandır seçeneğine tıkladım ve bir kaç dakika sonra res skili noneye döndü,

+öncelik atack yapmaya ayarlı öncelik kaldırmaya ayarlama özelliği varmı?

English:

In the skills advanced section, I select the auto revive instead of the res skill, I clicked the auto revive party members option and after a few minutes, the res skill changed to none,

+ Is there a feature to set priority to remove priority?

**Comment by SDClowen** [comment]
Fixed with this [commit](https://github.com/SDClowen/RSBot/commit/9dae574186f6607044243ac3a320e456d825ac77)
