### ISSUE TITLE
[Bug] Doesnt atack the bot.

### ISSUE THREAD

**Issue by iKornel** [SDClowen/RSBot#524]
Silkroad Online Global, Server: Philotes, mobs: lv101, 113-114, 115-116, 119
RSBot version: 2.4
I tried many things, added skills by all of mob type , does not recognize the mobs in the training area, just stay in the middle.

**Comment by dvdblk** [comment]
Already fixed in #514 , you have two options:

1. download the latest source code and compile rsbot.exe manually in Visual Studio, start the bot from there
2. wait for a new official release

**Comment by SDClowen** [comment]
Already fixed.
