### ISSUE TITLE
[Bug]Koruma Bölümünde Skill Kullanmama Sorunu

### ISSUE THREAD

**Issue by akulleci** [SDClowen/RSBot#525]
**Version (please complete the following information):**
 - SRO version: TrSRO
 - RSBot version (or commit): v2.4

**Describe the bug**
Koruma bölümünde mp % ? düşerse skill kullanma bölümü çalışmıyor.

**Comment by SDClowen** [comment]
Issue'ye bir başlık atın.

**Comment by akulleci** [comment]
Ayrıca Kötü duruma düştüğünde skill kullan bölümüde çalışmıyor. ( Denediğim build :  Bard.)
