### ISSUE TITLE
Specialty Goods Box Toplamıyor[Bug]

### ISSUE THREAD

**Issue by akulleci** [SDClowen/RSBot#533]
**Version (please complete the following information):**
 - SRO version: [e.g. TRSRO]
 - RSBot version (or commit): [e.g. v2.5.1]

**Describe the bug**
Job skilleri açık, eşya ayarlarından filtreledim fakat specialty good's boxları toplamıyor.

**Comment by Ahmed0425** [comment]
Can be duplicate to #32
