### ISSUE TITLE
Yeni Sürüm Yüklendiğinde Scriptlerin Silinmesi [Feature request]

### ISSUE THREAD

**Issue by akulleci** [SDClowen/RSBot#534]
**Describe the solution you'd like**
Yeni güncel sürümü yüklediğimizde ayarlarımız kaybolmuyor fakat kullandığımız scriptler kayboluyor. Scriptlerinde kaybolmaması için bişeyler yapılabilirse güzel olur.

**Comment by SDClowen** [comment]
![image](https://user-images.githubusercontent.com/14323838/199271582-a319fb0d-72e3-4813-b106-b77080001edf.png)
Bu seçenek bu yüzden eklendi. **[Delete old installation]** seçeneğini işaretlemezseniz eski kurulumun üzerine yazar. Yani sadece kendi dosyalarını değiştirir sizinkilere dokunmaz.
