### ISSUE TITLE
Auto PT Form Problem [Bug]

### ISSUE THREAD

**Issue by akulleci** [SDClowen/RSBot#535]
**Version (please complete the following information):**
 - SRO version: [e.g. TRSRO]
 - RSBot version (or commit): [e.g. v2.5.1]

**Describe the bug**
LTP'de iken party fullenip biri çıktığı zaman oto form yapmıyor. Oyundan manuel PT formlayınca düzeliyor.

**Comment by akulleci** [comment]
Üye sınırına ulaştığı halde pt göndermeye devam ediyor.

**Comment by SDClowen** [comment]
Fixed with v2.7
