### ISSUE TITLE
Add a new option Store items from pet(checkbox) to Items/Shopping/General setup(groupbox)

### ISSUE THREAD

**Issue by sakipvp** [SDClowen/RSBot#56]

**Comment by SDClowen** [comment]
What you mean here?

**Comment by sakipvp** [comment]
It is a double move when Player at storage, after move StoreItems from PlayerInventory to PlayerStorage
...
move StoreItems from PetInventory to PlayerInventory,
then move StoreItems from PlayerInventory to PlayerStorage
--
1. visualization
add Store items from pet checkbox to
Plugins/RSBot.Items/Views/Main/tabMain/Shopping tab/General setup groupbox
--
2. code
----
2.1. add new option to config file of Player
----
2.2. add to double move Libraries\RSBot.Core\Components
ShoppingManager.cs StoreItems method
(ScriptManager.cs, case "store")
