### ISSUE TITLE
[Bug] Automated Login doesn't work with RIGID files

### ISSUE THREAD

**Issue by BaroDevelopment** [SDClowen/RSBot#584]
**Version (please complete the following information):**
 - SRO version:  230
 - RSBot version latest

**Describe the bug**
Automated login is not working - i tried it with delay too but doesnt work
I have a csro server too and there it works - just not with RIGID files

**Comment by ahmed007boss** [comment]
This is very important issue I tried to fix it my self but it’s seems that rigid client doesn’t support switch to characters selection screen after sending login packet

**Comment by SDClowen** [comment]
Fixed with v2.7
