### ISSUE TITLE
Feature request-Suggestions for fixing and bugs

### ISSUE THREAD

**Issue by beibsia** [SDClowen/RSBot#589]
1-Potion veya durability düştüğünde şehire ışınlanıyor  hiçbirşey almayıp ve repair atmadan kasalıma alanına gidiyor.
2-Bot başlatıldığında çar party de değilse pet yada başka insanlara attack atıp pk oluyor.
3-Res skilini ayarlıyoruz hem res atmıyor ve none olarak geri sıfırlanıyor.
4-Lure atarken walk randomly yaptığımızda çar ilerliyor attack yapıp geri dönmüyor ayriyetten kendi scriptimi cizip kullandığım zaman takılarak koşuyor.
5- EU çarlarda buff basarken sürekli heal ve buff atıyor.

**Comment by beibsia** [comment]
6-Canavar tercihleri(avoidance) çalışmıyor skills bölümünden event moblarına attack yaptırıyorum event mobları genel olarak gözüküyor yani açıkçası event bomlarına attack yapmıyor
7-Çar bir yere takıldığında geri gitme gibi birşey olursa güzel olur
8-İtemleri pickup sell store bolumu çalışıyor ama herşeyi topluyor pickdown seçeneği gelirse güzel olu

**Comment by Ahmed0425** [comment]
next time open a separate issue for each one
second these are bugs and you should choose bug reports not feature request

**Comment by SDClowen** [comment]
Bu şekilde issue kabul edilmemektedir. Buradaki sorunların çoğu fixlendi ve v2.9 ile birlikte aktif olacak. Bir sonrakine her sorun başı burada bir issue açın!
