### ISSUE TITLE
[Bug] RİGİD  VERSİYON

### ISSUE THREAD

**Issue by emrinolur** [SDClowen/RSBot#590]
**Version (please complete the following information):**
 - SRO version: RİGİD
 - RSBot version (or commit): 30.12.2022 github versıon kullanıyorum ama hepsinde sorun var gordugum karıyla 

bot sorunsuz calısıyor ama 4 adet seyde sorun var gorduklerım

1- oto giris calısmıyor hıc bır sekılde calıstıramadım crash verıyor dc verıyor gırmıyor oto gırısı acınca
2- pet canlandırma yapmıyor ve pet cagırma yapmıyor
3- pet koruma sekmesınıde goremedım (peti koru kısmı yok)
4- birde char  ölünce ısınlanıyorum sehıre sorun yok ama ara ara yapıyor char takılı kalıyor hıc tepkı vermıyor kapatıp gırmek zorunda kalıyorum (fellow pet acık sekılde ) ondan olabılırmı bırde cok hızlı basıyorum sehıre ısınlan dıye oda olabılır

**Comment by SDClowen** [comment]
v2.6.3  indirip tekrar deneyin. Ayrıca her bir sorun için github üzerinde bir tane issue açın. Yani problem başına 1 issue!
