### ISSUE TITLE
[Bug] RİGİD

### ISSUE THREAD

**Issue by emrinolur** [SDClowen/RSBot#591]
**Version (please complete the following information):**
 - SRO version: RİGİD
 - RSBot version (or commit): 2.6.3 SON SURUM 

oto giris calısmıyor hıc bır sekılde calıstıramadım crash verıyor dc verıyor gırmıyor oto gırısı acınca (filter vs acık değil)

**Comment by SDClowen** [comment]
Issue açmadan var olan issueleri kontrol edin! #584

**Comment by SDClowen** [comment]
Issue açmadan önce var olan issueleri kontrol edin! #584
