### ISSUE TITLE
[Feature request] VSRO client version 1.192 support.

### ISSUE THREAD

**Issue by shinrel22** [SDClowen/RSBot#606]
I can't get the bot working for this version 1.192
I get disconected trying the login.
The client download link here
`https://download.ahi.mobi/v51/SROMAX_FileSP.rar`

**Comment by SDClowen** [comment]
![image](https://user-images.githubusercontent.com/14323838/217352453-356641e6-048f-4bae-86de-536b7e3f2825.png)
Select client type Vietnam193
