### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by megaman4999** [SDClowen/RSBot#608]
can you add a option where we can select for what the grabpet only can pickup while setting up item filter because it only allow us to select "pickup" or "pickup with character"

**Comment by SDClowen** [comment]
Interesting. You can do that with current state. 
Just check [Use grabpet for pickuping] on items plugin. If you didn't select "pickup only character" the item will collect other items with grabpet.

**Comment by megaman4999** [comment]
well i prefer the grabpet to pickup tablet/stones/elixirs/gold and char to picks up items to auto sell at npc
