### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by huzeyfe441** [SDClowen/RSBot#633]
**Version (please complete the following information):**
 - SRO version: [TRSRO]
 - RSBot version (or commit): [2.8]

**Describe the bug**
When we start the bot, it mostly staggers on its way to kill the creature.
Anyone know about the solution?

Botu çalıştırdığımızda çoğunlukla kesik kesik (saniyelik duraksayarak) yaratığı öldürme yolunda ilerliyor.
Çözümü hakkında bilgisi olan var mı ?

**Comment by Ann1335** [comment]
you can test change EnableAbilityPet = false, maybe will fix.
