### ISSUE TITLE
Trojan flags on Virustotal

### ISSUE THREAD

**Issue by DoYouNotice** [SDClowen/RSBot#638]
Can u try to reduce the flags on virustotal there is a few trojan flags

https://www.virustotal.com/gui/file/852e895dd1cc818abc75f5af658a283ddbc06d70bb8022a2cd6699d03d98be7a/detection

**Comment by SDClowen** [comment]
False positive viruses. Download and build the project source code from this repository. Submit RSBot.dll and Client.Library.dll files to virustotal and you will see false positive viruses. That means viruses show in clean code, no real virus.
