### ISSUE TITLE
[Bug] Windows 11 bot does not recognize anything from client

### ISSUE THREAD

**Issue by benossa** [SDClowen/RSBot#650]
- SRO version: GSRO v.1.318 from gsro.fun
 - RSBot version 2.9

I can start the client with btn "Start Client" and I login to character, but nothing gets loaded into bot from SRO
On top of the form is message "Not in game".
I do not see my skills, items or even coordinates.
I have tried every type of client settings (Vietnam, Turkey, Chinese... and seems to Global is good one)
I also tried compatible mode set on Windows 8, didn't helped.

Os is Windows 11 Pro 22H2 

![image](https://github.com/SDClowen/RSBot/assets/12429119/eefb32a1-d936-4f53-b9ed-c7f526f4dfc4)

**Comment by benossa** [comment]
Can you read what I wrote in the post ?
You think I haven't tried that before posting ?
I have tried every possible combination of setting which include every locale, run as administrator, compatibility as Windows 7 and 8. And bot is still not wokring 

> Choose "Vietnam" on the right beside the exe path and close this trash!

**Comment by Ahmed0425** [comment]
Then must be either related to the filter or packed client!
either way it's related to the server and the client not the bot

**Comment by EvilNiqht** [comment]
Can you put the items in the inventory in the storage and try again?

**Comment by benossa** [comment]
> Then must be either related to the filter or packed client! either way it's related to the server and the client not the bot

We do not know that untill someone with working bot downloads GSRO client and confirm the same issue. Only then we know that it's client fault.

**Comment by benossa** [comment]
Vietnam locale is now working, im not sure what caused this error but bot started working the next day. Also skills were not listed in their real name instead databse names, but after bot restart, skills had their correct names.
