### ISSUE TITLE
UPNP lock

### ISSUE THREAD

**Issue by Burnpoint** [SDClowen/RSBot#651]
**Version (please complete the following information):**
 - SRO version: [vsro client]

**Describe the bug**
Englisch

Starting the game with the bot works, but the bot cannot log in because there is a UPNP lock

[06:15:35]	<Notify> 	This client is up to date, no patch required!

**(Optional) Screenshots**
[https://i.ibb.co/TbvPgj0/Unbenannt.png](url)

**Comment by SDClowen** [comment]
This is not RSBot related talk with your game admin for about the problem.
