### ISSUE TITLE
                   rsbot v 2.9[Bug]Trsro Version: 1.033  When he returns to the city when buying hp + mp he gets kicked out of the server and when he tries to re-enter he gets kicked again I have to close rsbot and reopen it happens every time he tries to buy hp + mp

### ISSUE THREAD

**Issue by Nero2200** [SDClowen/RSBot#652]
**Version (please complete the following information):**
 - SRO version: [e.g. iSRO]
 - RSBot version (or commit): [e.g. v2.3]

**Describe the bug**

**To reproduce the behavior:**
1. Walk to Samarkand
2. Start bot
3. Get disconnected from the server

**(Optional) Screenshots**

**Comment by sumsurat** [comment]
SW TRsro Oyunda Bug Var Şehre Gitginde Pot almak icin Oyundan Atıyo Rsbot Çöküyo Ve Tekrardan Kapatıp Acmak Zorunda Kalıyoruz Bot Çöküyo Şehire Işınlanınca Yada Dirildiginde Şehre Dödügünde Kople Çöküyo Yardım Edin Lütfen

**Comment by Matron10** [comment]
> 

a mi me pasa cuando uso ferry llevando trader o cuando compro merca de trader
