### ISSUE TITLE
[Feature suggest] Button for training on Map tab.

### ISSUE THREAD

**Issue by benossa** [SDClowen/RSBot#653]
I think it would be helpful to add just one more button on tab where is map shown
so I can see training area on map and adjust it if needed, also if playing clientless, it would be easier to change training spot.
I have made an mockup of my idea on image

![map feature](https://github.com/SDClowen/RSBot/assets/12429119/26da7230-9ccc-4694-bc2d-d4842e4a8ef8)

**Comment by SDClowen** [comment]
You can use the training plugin for this after moving on the map. Otherwise, it will be a crowded view. Thanks for your suggestion.
