### ISSUE TITLE
[Bug] Pet auto HP Recovery doesn't work

### ISSUE THREAD

**Issue by pablo0111** [SDClowen/RSBot#662]
**Version (please complete the following information):**
 - SRO version: [e.g. iSRO]  sro 188 private server
 - RSBot version (or commit):  2.9

**Describe the bug**
On "protection" on "Recovery - pet" i got checked USE HP potions if HP < % and it doesnt work on attack pet or transport when trading.

**To reproduce the behavior:**
1. Go to any place to hunt or start a trade
2. start bot
3. pet hp goes down until it die

**(Optional) Screenshots**
N/A

I've read that this server might change some default values and you need to verify it to fix it.

**Comment by SDClowen** [comment]
Set title to your issue please
