### ISSUE TITLE
[Bug] İSRO CLİENT START BUG

### ISSUE THREAD

**Issue by emrinolur** [SDClowen/RSBot#716]
**Version (please complete the following information):**
 - SRO version: [iSRO]
 - RSBot version (or commit): [latest updated version 13.09.2023-13:37]

Client Başlat dedikten sonra başlamıyor sureklı açıp kapatmak gerekiyor botu
![Ekran Görüntüsü (542)](https://github.com/SDClowen/RSBot/assets/99028246/2c52262e-8ec5-4ff2-b168-5149878bf968)
![Ekran Görüntüsü (543)](https://github.com/SDClowen/RSBot/assets/99028246/006713e5-f875-4703-a2b7-0c3402e2f034)
![Ekran Görüntüsü (544)](https://github.com/SDClowen/RSBot/assets/99028246/b662a00c-8aaf-4706-9852-109d9cb8dbe2)

**Comment by SDClowen** [comment]
Botu kapatıp https://github.com/sdclowen/rsbot/releases adresinden son versiyonu indirin. Dosyada bloklama olup olmadığını kontrol etmek için sağ tıklayıp özellikler > engellemeyi kaldır düğmesine basın. Ardından botu zip dosyasından çıkarıp çalıştırın. Bu işlemleri yaptıktan sonra sorununuz hala devam ediyorsa botu başka bir diske taşıyıp deneyebilirsiniz.
