### ISSUE TITLE
[Bug] Can't start the VTC Game client

### ISSUE THREAD

**Issue by huynhducapd** [SDClowen/RSBot#722]
**Version (please complete the following information):**
 - SRO version: [VTC Game]
 - RSBot version (or commit): [e.g. v2.9.3]

**Describe the bug**
I can't use Start Client in bot to open the game anymore after new version of game update

**To reproduce the behavior:**
1. Walk to Samarkand
2. Start bot
3. Get disconnected from the server

![image](https://github.com/SDClowen/RSBot/assets/146050239/fb826c08-39bf-4818-81b3-c69328553425)
![image](https://github.com/SDClowen/RSBot/assets/146050239/e51a1f35-f882-4f6e-b5e3-57d7872999ee)

**Comment by lucthanca** [comment]
#725

**Comment by SDClowen** [comment]
Fixed. It will be apply with next release
