### ISSUE TITLE
[Bug] Not compatible with VTC client after client updating 26/09

### ISSUE THREAD

**Issue by rinoax113** [SDClowen/RSBot#724]
Thank you very much for creating this free bot <3
Hopefully someone can check VTC client after client updating ^^~

**Comment by rinoax113** [comment]
After update game, copy sro_client.exe from old version, replace it, then start BOT. It worked for me

**Comment by mbeef53** [comment]
Where do you get the old sro_client.exe after update? can you share it with me @rinoax113

**Comment by rinoax113** [comment]
> Where do you get the old sro_client.exe after update? can you share it with me @rinoax113

Download old version from home page of VTC silkroad, install old version, then copy sro_client.exe from installed folder

**Comment by mbeef53** [comment]
How do you install the old version, I tried to install and it keep asking if i wanted to remove the existing version @rinoax113

**Comment by rinoax113** [comment]
> How do you install the old version, I tried to install and it keep asking if i wanted to remove the existing version @rinoax113

Ok, you remove existing version, then install old version. After installed old version, copy sro_client to other folder. Next, update game, then copy back old sro_client to replace

**Comment by neofpt** [comment]
> B
it's work. nice try kkk

**Comment by Namdeptrai87** [comment]
I did as you did, copied the old cline out and copied it in. But after a short while, the client was out

**Comment by rinoax113** [comment]
Are you still VIP ?

**Comment by rinoax113** [comment]
> I did as you did, copied the old cline out and copied it in. But after a short while, the client was out

Try download my old sro client https://uploadnow.io/f/XpNcVGN
Remember turn off auto in game

**Comment by huynhducapd** [comment]
Bạn làm được không giải thích hộ mình với lú quá @Namdeptrai87

**Comment by rinoax113** [comment]
> Bạn làm được không giải thích hộ mình với lú quá @Namdeptrai87

Down client ở link google driver trên rồi copy đè vào folder game là chạy được bot bạn nhé

**Comment by huynhducapd** [comment]
Có cần xóa client cũ k hay vẫn để chung 1 folder là được b nhỉ @rinoax113

**Comment by rinoax113** [comment]
> Có cần xóa client cũ k hay vẫn để chung 1 folder là được b nhỉ @rinoax113

Bạn đổi tên sro_client.exe hiện tại thành tên khác, ví dụ sro_clientABC.exe, sau đó thì copy cái sro_client down từ google drive vào cho yên tâm

**Comment by huynhducapd** [comment]
> Author

Đã thành công. Đội ơn bác

**Comment by huynhducapd** [comment]
> > Có cần xóa client cũ k hay vẫn để chung 1 folder là được b nhỉ @rinoax113
> 
> Bạn đổi tên sro_client.exe hiện tại thành tên khác, ví dụ sro_clientABC.exe, sau đó thì copy cái sro_client down từ google drive vào cho yên tâm

Đã thành công, Đội ơn bác @rinoax113

**Comment by huynhducapd** [comment]
@rinoax113 Nếu bác còn ở đây thì e muốn hỏi bác là lần cập nhật này bác đã fix được chưa. Của em lại bị nữa rồi. Nếu bác có cách gì mong bác phỏ độ chúng sinh share cho em với ạ. Đội ơn bác

**Comment by rinoax113** [comment]
> @rinoax113 Nếu bác còn ở đây thì e muốn hỏi bác là lần cập nhật này bác đã fix được chưa. Của em lại bị nữa rồi. Nếu bác có cách gì mong bác phỏ độ chúng sinh share cho em với ạ. Đội ơn bác

Tối làm về mình check nhé, các bạn cứ vào nhóm discord để cập nhật cho nhanh

**Comment by huynhducapd** [comment]
> > @rinoax113 Nếu bác còn ở đây thì e muốn hỏi bác là lần cập nhật này bác đã fix được chưa. Của em lại bị nữa rồi. Nếu bác có cách gì mong bác phỏ độ chúng sinh share cho em với ạ. Đội ơn bác
> 
> Tối làm về mình check nhé, các bạn cứ vào nhóm discord để cập nhật cho nhanh

À e fix được r ạ, vẫn down client ở link kia về thay vào là đợc :v

**Comment by rinoax113** [comment]
> > > @rinoax113 Nếu bác còn ở đây thì e muốn hỏi bác là lần cập nhật này bác đã fix được chưa. Của em lại bị nữa rồi. Nếu bác có cách gì mong bác phỏ độ chúng sinh share cho em với ạ. Đội ơn bác
> > 
> > 
> > Tối làm về mình check nhé, các bạn cứ vào nhóm discord để cập nhật cho nhanh
> 
> À e fix được r ạ, vẫn down client ở link kia về thay vào là đợc :v

Bạn đang chạy bản bot version bao nhiêu, bản client của mình chỉ chạy được bản 2.9.3 đổ xuống thôi.

**Comment by huynhducapd** [comment]
> > > > @rinoax113 Nếu bác còn ở đây thì e muốn hỏi bác là lần cập nhật này bác đã fix được chưa. Của em lại bị nữa rồi. Nếu bác có cách gì mong bác phỏ độ chúng sinh share cho em với ạ. Đội ơn bác
> > > 
> > > 
> > > Tối làm về mình check nhé, các bạn cứ vào nhóm discord để cập nhật cho nhanh
> > 
> > 
> > À e fix được r ạ, vẫn down client ở link kia về thay vào là đợc :v
> 
> Bạn đang chạy bản bot version bao nhiêu, bản client của mình chỉ chạy được bản 2.9.3 đổ xuống thôi.

v1.011 bác ạ
