### ISSUE TITLE
[Bug] The game client could not starting, please try again later

### ISSUE THREAD

**Issue by evilsh** [SDClowen/RSBot#789]
**Version**
 - SRO version: [ iSRO]
 - RSBot version: [v2.9.7]

**Describe the bug**
once i try to start client through bot it shows nothing and in log shows The game client could not start, please try again later.

![Uploading Capture.JPG…]()

**Comment by goco58** [comment]
BURDADA FAALİYET YOK SANIRIM :=)))

**Comment by phat-crypto** [comment]
We have difficulty playing the
game because we can't use the
admin bug

**Comment by goco58** [comment]
HALAMI  İLGİLENEN YOK DEMEKKİ GERCEKTEN  BIRAKMIS  HERKES

**Comment by smd1729** [comment]
So what is the solution?
