### ISSUE TITLE
[Bug]RSBot Compiled Show Total White Window

### ISSUE THREAD

**Issue by LievreAI** [SDClowen/RSBot#798]
@SDClowen 
the tool style have error

Main Window
![image](https://github.com/user-attachments/assets/4d433cb1-eb09-4f52-b6c0-e74c358b99e6)

Training Window

![image](https://github.com/user-attachments/assets/43d05884-4c62-452f-a4e7-f84942a41994)

Skill Window

![image](https://github.com/user-attachments/assets/1d3c4044-1360-419a-a4f2-d41367e666f0)

Log Window

![image](https://github.com/user-attachments/assets/699979e4-c5a9-411a-9fd8-1300881f46ec)

-------------------
Dark Theme

Main Window

![image](https://github.com/user-attachments/assets/622015bc-d6e9-4fb8-b500-262b699986d2)

Training Window

![image](https://github.com/user-attachments/assets/49cab6a5-4e8e-48f7-a560-9e25ea0413ec)

Skill Window

![image](https://github.com/user-attachments/assets/fac2399b-dcfc-4da9-87a6-6fa476892506)

Log Window

![image](https://github.com/user-attachments/assets/8173c330-fb5f-44cc-9198-392aa651478a)

i dont think i really need to add more , the images show the error however if i replace the exe of the tool in other version its work perfect why under compiled version its not i cant explain it its generate log error

**Comment by SDClowen** [comment]
Update your submodules with `git submodule update --recursive --remote` and build again
