### ISSUE TITLE
pressing alt while botting gets me pk

### ISSUE THREAD

**Issue by Ahmed0425** [SDClowen/RSBot#85]
When I press alt button while botting, the bot attacks other players and I get pk

**Comment by SDClowen** [comment]
With last source or 1.6?

**Comment by TheRock2007** [comment]
1.6

**Comment by Ahmed0425** [comment]
Please wait I'll ask my friend who discovered the bug and made me write it
I sent him a fresh build though so I may get a clear answer

**Comment by SDClowen** [comment]
I fixed that. It will be apply in v1.7b

**Comment by TheRock2007** [comment]
not fixed  in last update bot

**Comment by SDClowen** [comment]
Make a video please. I didnt saw any problem with last source code!
