### ISSUE TITLE
Fix bug in Library\RSBot.Core\Components\SpawnManager.cs GetEntity method

### ISSUE THREAD

**Issue by sakipvp** [SDClowen/RSBot#97]
CASE: (p as T) == null
CURRENT, BAD code: return (T)_entities.Find(p => condition(p as T));
NEW, CORRECT code: return (T)_entities.Find(p => ((p as T) != null) && condition(p as T));

**Comment by SDClowen** [comment]
If you sure its correct you can create a pull request instead of write a issue!
