### ISSUE TITLE
Fix bug in Library\RSBot.Core\Components\ScriptManager.cs ExecuteTeleport method

### ISSUE THREAD

**Issue by sakipvp** [SDClowen/RSBot#98]
CASE: wrong Entity type
CURRENT, BAD code: if (!SpawnManager.TryGetEntity<SpawnedNpcNpc>
NEW, CORRECT code: if (!SpawnManager.TryGetEntity<SpawnedPortal>

**Comment by sakipvp** [comment]
... github delete my full comment
CURRENT, BAD type: SpawnedNpcNpc
NEW, CORRECT type: SpawnedPortal

**Comment by SDClowen** [comment]
Learn git please!
